select * from orders
select * from products
select * from users

--Q1. List the total number of orders for each product, sorted by the number of orders

select p.productname as product, sum(o.orderid) as total_orders
from orders o
inner join products p
on o.productid=p.productid
group by 1
order by 2


--Q2.Find the total revenue generated by each user.

select extract(year from orderdate) as year, sum(amount) as revenue
from orders
group by 1

--Q3.Display users who have not placed any orders.

select userid as users from orders
where orderid is null






